remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: RBR Co Driver Mod
description: [A short description of your site's purpose]
show_downloads: true
github:
  zip_url: https://github.com/rbrdarren/rbrdarren.github.io/releases/download/v1.0-rc2.1/Darren.Standard.Numeric.RC2.1.zip
